name: Build docker image

on:
  push:
    branches:
    - master
    paths-ignore:
    - DeAtChVoteBot/Resources/**
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build docker image
      run: docker build . --file ./DeAtChVoteBot/Dockerfile --tag olfi01/deatchvote
    - name: Push the Docker image
      if: ${{ github.event_name == 'push' }}
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push olfi01/deatchvote


